# Решение заданий к уроку 1

## Часть 1


**__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:**

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


### Решение

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   Произведение этих матриц не определено, так как количество столбцов матрицы А (=2) не соответствует количеству строк матрицы В (=4)
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   Произведение этих матриц определено и размер результирующей матрицы будет $2\times 3$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   Произведение этих матриц определено и размер результирующей матрицы будет $8\times 8$
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

   Произведение этих матриц определено и размер результирующей матрицы будет $4\times 4$
    

**__2.__ Найти сумму и произведение матриц** $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



### Решение

$A + B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}  + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix} $

$A \cdot B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}  \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
{4} & {-1-10}\\ 
{12} & {-3}
\end{pmatrix} = \begin{pmatrix}
{4} & {-11}\\ 
{12} & {-3}
\end{pmatrix}$



In [40]:
# проверим
import numpy as np
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1],[0,5]])
print(f'A+B = \n{A+B}, \nA*B = \n{A.dot(B)}')


A+B = 
[[ 5 -3]
 [ 3  5]], 
A*B = 
[[  4 -11]
 [ 12  -3]]


**__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц** $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    


### Решение

$3A-2B+4C = 3 \cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+ 4 \cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
{3-0+8} & {21-10-16}\\ 
{9-4+4} & {-18+2+4}
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [6]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
3*A -2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

**__4.__ Дана матрица** $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
**Вычислить** $AA^{T}$ и $A^{T}A$ 



### Решение

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}, \,\,\,\, A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 &3 
\end{pmatrix}$

$A\cdot A^T=\begin{pmatrix}
{16+1} & {20-2} & {8+3} \\ 
{20-2} & {25+4} & {10-6}\\ 
{8+3} & {10-6} &{4+9}
\end{pmatrix} =  \begin{pmatrix}
{17} & {18} & {11} \\ 
{18} & {29} & {4}\\ 
{11} & {4} &{13}
\end{pmatrix}$

$A^T\cdot A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 &3 
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
{16+25+4} & {4-10+6} \\ 
{4-10+6} & {1+4+9} 
\end{pmatrix} =  \begin{pmatrix}
{45} & {0} \\ 
{0} & {14} 
\end{pmatrix}$

In [23]:
A = np.array([[4,1],[5,-2],[2,3]])
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [9]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

### Решение

In [21]:
def matr_mult(A,B): #на вход подаются матрицы A размером m*n и B размером n*k 
  m = A.shape[0]
  n1 = A.shape[1]
  n2 = B.shape[0]
  if n1 == n2: # проверка что произведение матриц определено
    n = n1
  else:
    print(f'произведение матриц не определено')
    return False
  k = B.shape[1]
  C = np.zeros((m,k))
  for i in range(m):
    for j in range(k):
      for l in range(n): 
        C[i,j] +=A[i,l]*B[l,j] 
  return C



In [30]:
# определим матрицы
D = np.array([[1,2,3],[3,2,1]])
G = np.array([[1,2,3,3],[5,7,6,7],[4,2,1,0]])
print(D)
print(G)

[[1 2 3]
 [3 2 1]]
[[1 2 3 3]
 [5 7 6 7]
 [4 2 1 0]]


In [31]:
#проверим нашу функцию
matr_mult(D,G)

array([[23., 22., 18., 17.],
       [17., 22., 22., 23.]])

In [32]:
# проверим правильность вычисления:
D.dot(G)

array([[23, 22, 18, 17],
       [17, 22, 22, 23]])

In [33]:
# проверим случай когда произведение не определено
matr_mult(G,D)

произведение матриц не определено


False

## Часть 2

**__1.__ Вычислить определитель:**

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$




### Решение 
   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = \sin^2x + \cos^2x = 1$

   б)

так как матрица    $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$ треугольная, то определитель   $det = 4*5*9 = 180$ 
    
   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1*5*9+2*6*7+4*8*3 - 7*5*3-8*6*1-4*2*9 = 45+84+96-105-48-72 = 0$

In [35]:
H = np.array([
              [4,2,3],
              [0,5,1],
              [0,0,9]
              ])
np.linalg.det(H)

180.0

**__2.__ Определитель матрицы $A$ равен $4$. Найти:**

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   


### Решение

$det A = 4, \,\,\,$ тогда


   а) $det(A^{2}) = det (A\cdot A))= det A \cdot det A = 4*4 = 16$;
    
   б) $det(A^{T}) = det A = 4$;
    
   в) $det(2A)$ однозначно определить нельзя потому что множитель мы можем выносить только из строки или колонки. 
   
   Но если допустим что размер матриц = $n\times n$, тогда  
   
   $det(2A) = 2*n*det A = 8n $.

**__3.__  Доказать, что матрица**

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



### Решение

Умножим первую строку на -2

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}  = \begin{pmatrix}
4 & -14 & 6\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$

Выдим что первые две строки одинаковые , следовательно определитель такой матрицы будет равен 0 и матрица будет вырождена

In [37]:
# проверим
A1 = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(A1)

0.0

**__4.__ Найти ранг матрицы:**

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

### Решение

   а) можно заметить что в матрице $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} $ третья строка является суммой первых двух, следовательно третья строка является линейной комбинацией первых двух строк и для определения ранга матрицы ее можно выбросить. 
Строчный ранг оставшейся матрицы = 2, так как эти строки линейно не зависимы




   б) можно заметить что в матрице $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ третья строка является суммой первых двух, следовательно третья строка является линейной комбинацией первых двух строк и для определения ранга матрицы ее можно выбросить. Получим матрицу:

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ 

которая состоит из 3 линейно-назависимы строк, следовательно ранг матрицы = 3

In [38]:
# проверим
A2 = np.array([
               [1,2,3],
               [1,1,1],
               [2,3,4]
               ])
np.linalg.matrix_rank(A2)

2

In [39]:
A3 = np.array([
               [0,0,2,1],
               [0,0,2,2],
               [0,0,4,3],
               [2,3,5,6]
               ])
np.linalg.matrix_rank(A3)

3